#!/usr/bin/env python3
"""
PM Workflow Automator — AI-powered JIRA tools.

Default mode  : python pm_agent.py
  Fetches all issues from the KAN project and generates a structured
  sprint summary (priorities, blockers, in-progress/stalled, next actions).

Story drafter : python pm_agent.py --draft
  Accepts a plain-English idea, generates a complete JIRA ticket with
  Claude, reviews it with you, then optionally creates it in JIRA.
"""

import os
import sys

# Ensure Unicode output works on Windows terminals (cp1252 → utf-8).
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import argparse
import json
import requests
from dotenv import load_dotenv
import anthropic

# ─── Config ───────────────────────────────────────────────────────────────────

load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
JIRA_EMAIL        = os.getenv("JIRA_EMAIL")
JIRA_API_TOKEN    = os.getenv("JIRA_API_TOKEN")

JIRA_DOMAIN       = "saranshsworkspace-35970721.atlassian.net"
JIRA_PROJECT_KEY  = "KAN"
CLAUDE_MODEL      = "claude-sonnet-4-6"

# ─── Validation ───────────────────────────────────────────────────────────────

def validate_env() -> None:
    """Exit early with a clear message if any required variable is missing."""
    missing = [v for v in ("ANTHROPIC_API_KEY", "JIRA_EMAIL", "JIRA_API_TOKEN")
               if not os.getenv(v)]
    if missing:
        print(f"[error] Missing environment variables: {', '.join(missing)}")
        print("        Copy .env.example → .env and fill in your credentials.")
        sys.exit(1)

# ─── JIRA — read ──────────────────────────────────────────────────────────────

def fetch_jira_issues() -> list[dict]:
    """
    Query the JIRA REST API v3 for all issues in the KAN project.

    Returns a list of raw issue dicts sorted by priority (descending)
    and most-recently-updated first.
    """
    url     = f"https://{JIRA_DOMAIN}/rest/api/3/search/jql"
    auth    = (JIRA_EMAIL, JIRA_API_TOKEN)
    headers = {"Accept": "application/json"}
    params  = {
        "jql":        f"project = {JIRA_PROJECT_KEY} ORDER BY priority DESC, updated DESC",
        "fields":     "summary,status,issuetype,priority,assignee,description",
        "maxResults": 100,
    }

    try:
        response = requests.get(url, auth=auth, headers=headers, params=params, timeout=15)
        response.raise_for_status()
    except requests.exceptions.HTTPError as exc:
        print(f"[error] JIRA API returned an error: {exc}")
        sys.exit(1)
    except requests.exceptions.ConnectionError:
        print("[error] Could not reach JIRA. Check your domain and internet connection.")
        sys.exit(1)
    except requests.exceptions.Timeout:
        print("[error] JIRA request timed out. Try again in a moment.")
        sys.exit(1)

    issues = response.json().get("issues", [])

    if not issues:
        print(f"[info] No issues found in project {JIRA_PROJECT_KEY}. Nothing to summarize.")
        sys.exit(0)

    return issues


def format_issues_for_prompt(issues: list[dict]) -> str:
    """
    Convert raw JIRA issue objects into a compact, readable bullet list
    that fits neatly inside the Claude prompt.
    """
    lines = []
    for issue in issues:
        fields       = issue.get("fields", {})
        key          = issue.get("key", "???")
        summary      = fields.get("summary", "No summary")
        status       = (fields.get("status") or {}).get("name", "Unknown")
        issue_type   = (fields.get("issuetype") or {}).get("name", "Unknown")
        priority     = (fields.get("priority") or {}).get("name", "None")
        assignee_obj = fields.get("assignee") or {}
        assignee     = assignee_obj.get("displayName", "Unassigned")

        lines.append(
            f"- [{key}] {summary} "
            f"| Type: {issue_type} | Status: {status} "
            f"| Priority: {priority} | Assignee: {assignee}"
        )

    return "\n".join(lines)

# ─── JIRA — write ─────────────────────────────────────────────────────────────

def create_jira_ticket(ticket: dict) -> str | None:
    """
    POST a new issue to JIRA using the ticket dict generated by Claude.

    The description and acceptance criteria are formatted as Atlassian
    Document Format (ADF), which JIRA REST API v3 requires for rich text.

    Returns the browser URL of the created ticket, or None on failure.
    """
    url     = f"https://{JIRA_DOMAIN}/rest/api/3/issue"
    auth    = (JIRA_EMAIL, JIRA_API_TOKEN)
    headers = {"Accept": "application/json", "Content-Type": "application/json"}

    # Build ADF bullet list for acceptance criteria.
    ac_list_items = [
        {
            "type": "listItem",
            "content": [
                {"type": "paragraph", "content": [{"type": "text", "text": ac}]}
            ],
        }
        for ac in ticket["acceptance_criteria"]
    ]

    adf_description = {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": ticket["description"]}],
            },
            {
                "type": "paragraph",
                "content": [
                    {
                        "type": "text",
                        "text": "Acceptance Criteria",
                        "marks": [{"type": "strong"}],
                    }
                ],
            },
            {"type": "bulletList", "content": ac_list_items},
        ],
    }

    payload = {
        "fields": {
            "project":     {"key": JIRA_PROJECT_KEY},
            "summary":     ticket["title"],
            "issuetype":   {"name": ticket["issue_type"]},
            "priority":    {"name": ticket["priority"]},
            "description": adf_description,
        }
    }

    try:
        response = requests.post(url, auth=auth, headers=headers, json=payload, timeout=15)
        response.raise_for_status()
    except requests.exceptions.HTTPError as exc:
        print(f"[error] JIRA returned an error when creating the ticket: {exc}")
        print(f"        {exc.response.text}")
        return None

    key = response.json().get("key")
    return f"https://{JIRA_DOMAIN}/browse/{key}"

# ─── Claude — sprint summary ──────────────────────────────────────────────────

SUMMARY_SYSTEM_PROMPT = (
    "You are an experienced Product Manager and Agile coach. "
    "You analyze JIRA sprint data and produce clear, actionable summaries "
    "for development teams. Your output is direct, practical, and helps the "
    "team focus on what matters most right now."
)


def generate_sprint_summary(issues_text: str) -> str:
    """
    Send the formatted issue list to Claude and return the sprint summary.

    The system prompt is cached with ephemeral cache_control so that
    repeated runs don't re-process the same stable instructions.
    """
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    user_message = f"""Here are the current issues from our JIRA project ({JIRA_PROJECT_KEY}):

{issues_text}

Please provide a structured sprint summary with these four sections:

## Top 3 Priorities Right Now
List the 3 most important issues the team should focus on immediately, with brief reasoning.

## Blockers & Risks
Identify potential blockers, high-priority bugs, or risks that could derail the sprint.

## In Progress vs Stalled
Categorize what is actively moving forward versus what appears stuck or needs attention.

## Suggested Next Actions
Give 3-5 concrete, actionable recommendations for the team to improve velocity or address risks.

Keep the summary concise and actionable. Use bullet points where appropriate."""

    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=1500,
        system=[
            {
                "type": "text",
                "text": SUMMARY_SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{"role": "user", "content": user_message}],
    )

    return response.content[0].text

# ─── Claude — story drafter ───────────────────────────────────────────────────

DRAFTER_SYSTEM_PROMPT = (
    "You are a senior product manager who writes clear, precise JIRA tickets. "
    "You always respond with a single valid JSON object and nothing else — "
    "no markdown fences, no explanation, no preamble."
)


def generate_ticket_draft(idea: str) -> dict | None:
    """
    Send a plain-English idea to Claude and get back a structured ticket dict.

    Claude is instructed to return raw JSON so we can parse and display it
    before optionally posting it to JIRA.
    """
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    user_message = f"""Convert this rough idea into a structured JIRA ticket:

"{idea}"

Respond with ONLY a JSON object in this exact format (no markdown, no extra text):
{{
  "title": "concise action-oriented title, max 10 words",
  "issue_type": "Story",
  "priority": "High",
  "priority_reasoning": "one sentence explaining the priority choice",
  "description": "2-3 sentences of user-facing context explaining what and why",
  "acceptance_criteria": [
    "testable criterion 1",
    "testable criterion 2",
    "testable criterion 3"
  ]
}}

Rules:
- issue_type must be exactly one of: Story, Task, Bug
- priority must be exactly one of: High, Medium, Low
- acceptance_criteria must have 3-5 items, each independently testable"""

    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=800,
        system=[
            {
                "type": "text",
                "text": DRAFTER_SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{"role": "user", "content": user_message}],
    )

    raw = response.content[0].text.strip()

    # Strip markdown code fences if Claude added them despite instructions.
    if raw.startswith("```"):
        raw = raw.strip("`").lstrip("json").strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        print(f"[error] Could not parse Claude's response as JSON:\n{raw}")
        return None

# ─── Output helpers ───────────────────────────────────────────────────────────

def print_summary(summary: str, issue_count: int) -> None:
    """Render the sprint summary with clean section headers in the terminal."""
    width = 70
    print(f"\n{'=' * width}")
    print(f"  AI PM SPRINT SUMMARY  |  Project: {JIRA_PROJECT_KEY}  |  {issue_count} issues analyzed")
    print(f"{'=' * width}\n")
    print(summary)
    print(f"\n{'-' * width}")
    print(f"  Model: {CLAUDE_MODEL}")
    print(f"{'-' * width}\n")


def print_ticket_preview(ticket: dict) -> None:
    """Render the generated ticket in a readable terminal format."""
    width = 70
    print(f"\n{'=' * width}")
    print(f"  GENERATED TICKET PREVIEW")
    print(f"{'=' * width}")
    print(f"\n  Title       : {ticket['title']}")
    print(f"  Type        : {ticket['issue_type']}")
    print(f"  Priority    : {ticket['priority']}  —  {ticket['priority_reasoning']}")
    print(f"\n  Description :")
    print(f"  {ticket['description']}")
    print(f"\n  Acceptance Criteria:")
    for i, ac in enumerate(ticket["acceptance_criteria"], 1):
        print(f"    {i}. {ac}")
    print(f"\n{'=' * width}")

# ─── Modes ────────────────────────────────────────────────────────────────────

def run_sprint_summary() -> None:
    """Default mode: fetch all KAN issues and generate a sprint summary."""
    print(f"\n[PM Agent] Starting up …")
    print(f"[PM Agent] Fetching issues from JIRA project: {JIRA_PROJECT_KEY} …")

    issues = fetch_jira_issues()
    print(f"[PM Agent] Fetched {len(issues)} issue(s). Sending to Claude for analysis …")

    issues_text = format_issues_for_prompt(issues)

    try:
        summary = generate_sprint_summary(issues_text)
    except anthropic.AuthenticationError:
        print("[error] Invalid ANTHROPIC_API_KEY. Check your .env file.")
        sys.exit(1)
    except anthropic.APIError as exc:
        print(f"[error] Claude API error: {exc}")
        sys.exit(1)

    print_summary(summary, len(issues))


def run_story_drafter() -> None:
    """Draft mode: turn a plain-English idea into a JIRA ticket via Claude."""
    print("\n[Story Drafter] Describe your idea in plain English.")
    print("  Example: 'users should be able to reset their password from the login page'\n")

    idea = input("> ").strip()
    if not idea:
        print("[error] No idea entered. Exiting.")
        sys.exit(1)

    print("\n[Story Drafter] Generating ticket …")

    try:
        ticket = generate_ticket_draft(idea)
    except anthropic.AuthenticationError:
        print("[error] Invalid ANTHROPIC_API_KEY. Check your .env file.")
        sys.exit(1)
    except anthropic.APIError as exc:
        print(f"[error] Claude API error: {exc}")
        sys.exit(1)

    if ticket is None:
        sys.exit(1)

    print_ticket_preview(ticket)

    answer = input("\nCreate this in JIRA? (y/n): ").strip().lower()
    if answer != "y":
        print("\n[Story Drafter] Ticket discarded. Run again to try a different idea.\n")
        return

    print("\n[Story Drafter] Creating ticket in JIRA …")
    url = create_jira_ticket(ticket)

    if url:
        print(f"\n[Story Drafter] Done!  {url}\n")

# ─── Entry point ──────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="PM Copilot — AI-powered JIRA tools",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  python pm_agent.py           # sprint summary\n"
            "  python pm_agent.py --draft   # story drafter\n"
        ),
    )
    parser.add_argument(
        "--draft",
        action="store_true",
        help="Turn a plain-English idea into a structured JIRA ticket",
    )
    args = parser.parse_args()

    validate_env()

    if args.draft:
        run_story_drafter()
    else:
        run_sprint_summary()


if __name__ == "__main__":
    main()
